version: "3.9"

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: dev
    ports:
      - "8501:8501"
    environment:
      - ENV_MODE=dev
    volumes:
      - .:/app
    command: streamlit run src/agents/Home.py --server.port=8501 --server.address=0.0.0.0

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: dev
    ports:
      - "8888:8888"
    environment:
      - ENV_MODE=dev
    volumes:
      - .:/app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root
